### PR TITLE
migrating for PR on server fixing naming conversions

### PR DESCRIPTION
**Pull request by cMoney667**
Fixed app to reflect new songs attributes.. tested in beta looks good. These changes are in reference to https://github.com/Chattahooligans/hooligan-hymnal-server/pull/47

### CODE REVIEW

**Comment by galenriley** [comment]
I think all this is in master branch already?

**Comment by galenriley** [comment]
https://github.com/Chattahooligans/hooligan-hymnal-app/commit/4f129bd38f5539c6fced0ccf0d98ab6018e6d61c

**Comment by cMoney667** [comment]
Will try pulling it down again wasn’t seeing it earlier my bad.

**Comment by cMoney667** [comment]
Looking at the files with fresh eyes this morning.. it looks like there were just a few places where something might have been overlooked @galenriley

**Pull request merged**
